### ISSUE TITLE
Requerimientos erroneos para windows

### ISSUE THREAD

**Issue by cartovarc** [AdminERP/ERPAdmin#4]
pkg-resources==0.0.0

Al hacer el "pip install -r requirements.txt"

Me tira un error por el pkg-resources, segun lei, es un problema del ubuntu y no deberia estar en los requerimientos.

**Comment by luishgranja** [comment]
Ese paquete lo genera cuando se hace pip freeze y no habia revisado cual era su utilidad. asi que si no te genera problema podes borrarlo.

mas info.
https://stackoverflow.com/a/39638060
