### ISSUE TITLE
Login y logout

### ISSUE THREAD

**Issue by cjcruzrivera** [AdminERP/ERPAdmin#9]
Al realizar el login redirecciona a /accounts/profile/ la cual no es una url valida. 
Al realizar el logout redirecciona al login del admin de django

**Comment by luishgranja** [comment]
Descargar el [settings.py](https://drive.google.com/file/d/1jwOzGao3aqZjwQTXcE27pduBF1OxbywJ/view) , hay unas variables necesarias para el login y logout.

Borrar de la declaracion de INSTALLED_APPS las apps que no necesita y llenar los datos de la base de datos. Recordar hacer las migraciones correspondientes.

Probar y dar feedback.

**Comment by cjcruzrivera** [comment]
Solucionado. Gracias
